services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - chromium
    networks:
      - app_net
  chromium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 1g
    ports:
      - 4444:4444
    logging:
      driver: none
    networks:
      - app_net
networks:
  app_net:
