services:
  app:
    build: .
    # command: sleep infinity
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - ..:/workspaces:cached
    ports:
      - "3000:3000"
    depends_on:
      chromium:
        condition: service_healthy
    networks:
      - app_net
  chromium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 1g
    environment:
      # - SE_NODE_MAX_SESSIONS=2
      # - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      # Disable Xvfb if running headless
      # - SE_START_XVFB=false 

      # Options for long-running containers
      # SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP= # default value false, set to true to enable the cleanup.
      # SE_BROWSER_LEFTOVERS_INTERVAL_SECS= # default value 3600 (1 hour), cleanup interval in seconds.
      # SE_BROWSER_LEFTOVERS_PROCESSES_SECS= # default value 7200 (2 hours), browsers running for longer than this time will be killed.
      # SE_BROWSER_LEFTOVERS_TEMPFILES_DAYS= # default value 1 (1 day), files generated by Chrome-based browsers in /tmp will be removed after these number of days (ignored when using Firefox).
    ports:
      - 4444:4444
    logging:
      driver: none
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  app_net:
